/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gatesecuretrial;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import net.proteanit.sql.DbUtils;
public class Profile extends javax.swing.JFrame {

    Connection serverString = null;
    PreparedStatement pStatement = null;
    ResultSet rSet = null;
   
    
    
    public Profile() throws SQLException {
        String dbFilePath = new String("jdbc:mysql://localhost/jvpapd?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC");
        String dbUsername = new String("root");
        String dbPassword = new String("1234");
        initComponents();
        serverString = DriverManager.getConnection(dbFilePath,dbUsername,dbPassword);
        showTableData();
         groupButton();
          jTextField_barcode.setVisible(false);
         jLabel_barcode.setVisible(false);
//         jPanel_Table.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_platenumber = new javax.swing.JTextField();
        jTextField_vehicleType = new javax.swing.JTextField();
        jTextField_firstName = new javax.swing.JTextField();
        jTextField_lastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton_submit = new javax.swing.JButton();
        jComboBox_gatepassType = new javax.swing.JComboBox<>();
        jLabel_barcode = new javax.swing.JLabel();
        jTextField_barcode = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton_add = new javax.swing.JRadioButton();
        jRadioButton_edit = new javax.swing.JRadioButton();
        jRadioButton_delete = new javax.swing.JRadioButton();
        jPanel_Table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Platenumber");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 129, -1, 34));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Gatepass Type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 83, -1, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Vehicle Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 169, -1, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Firstname");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 227, -1, -1));

        jTextField_platenumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_platenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 129, 112, -1));

        jTextField_vehicleType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_vehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 169, 112, -1));

        jTextField_firstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 224, 112, -1));

        jTextField_lastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 264, 112, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Lastname");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 258, -1, 34));

        jButton_submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_submit.setText("Submit");
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });
        jButton_submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_submitKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton_submitKeyTyped(evt);
            }
        });
        jPanel1.add(jButton_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 361, -1, -1));

        jComboBox_gatepassType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_gatepassType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Student", "DropOff/PickUp", "Delivery" }));
        jPanel1.add(jComboBox_gatepassType, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 89, 112, -1));

        jLabel_barcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_barcode.setText("Barcode");
        jPanel1.add(jLabel_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 303, -1, 34));

        jTextField_barcode.setEditable(false);
        jTextField_barcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_barcode.setEnabled(false);
        jPanel1.add(jTextField_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 303, 112, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jRadioButton_add.setSelected(true);
        jRadioButton_add.setText("Add");
        jRadioButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_addActionPerformed(evt);
            }
        });

        jRadioButton_edit.setText("Edit");
        jRadioButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_editActionPerformed(evt);
            }
        });

        jRadioButton_delete.setText("Delete");
        jRadioButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton_add)
                .addGap(39, 39, 39)
                .addComponent(jRadioButton_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jRadioButton_delete)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_add)
                    .addComponent(jRadioButton_edit)
                    .addComponent(jRadioButton_delete))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 11, -1, -1));

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 102), new java.awt.Color(51, 153, 0), new java.awt.Color(102, 102, 255), new java.awt.Color(153, 153, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setEditingColumn(11111);
        jTable1.setEditingRow(11111);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel_TableLayout = new javax.swing.GroupLayout(jPanel_Table);
        jPanel_Table.setLayout(jPanel_TableLayout);
        jPanel_TableLayout.setHorizontalGroup(
            jPanel_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel_TableLayout.setVerticalGroup(
            jPanel_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1.add(jPanel_Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 11, 620, -1));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
      
        if (jRadioButton_add.isSelected() == true) {
            insertUserDetailsToProfile();
           
        }
        if (jRadioButton_edit.isSelected() == true){
            updateUserDetailsToProfile();
            
        }
        if(jRadioButton_delete.isSelected() == true){
          
            deleteUserDetailsFromProfile();
        }
        showTableData();
        
    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jRadioButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_editActionPerformed
        jTextField_barcode.setVisible(true);
         jLabel_barcode.setVisible(true);
    }//GEN-LAST:event_jRadioButton_editActionPerformed

    private void jRadioButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_addActionPerformed
        jTextField_barcode.setVisible(false);
         jLabel_barcode.setVisible(false);
    }//GEN-LAST:event_jRadioButton_addActionPerformed

    private void jRadioButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_deleteActionPerformed
         jButton_submit.setText("Delete");
         jTextField_barcode.setVisible(true);
         jLabel_barcode.setVisible(true);
    }//GEN-LAST:event_jRadioButton_deleteActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       transferTableDataToTextField();             
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_submitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_submitKeyPressed
       
    }//GEN-LAST:event_jButton_submitKeyPressed

    private void jButton_submitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_submitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_submitKeyTyped

    
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Profile().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    
           
    
    private void groupButton( ) {

        ButtonGroup bgOptions = new ButtonGroup( );

        bgOptions.add(jRadioButton_add);
        bgOptions.add(jRadioButton_edit);
        bgOptions.add(jRadioButton_delete);

}
    
    private void insertUserDetailsToProfile(){
        try{
            
            
            if (jTextField_firstName.getText().isEmpty() || jTextField_lastName.getText().isEmpty() || jTextField_platenumber.getText().isEmpty() || jTextField_vehicleType.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Fill in All Fields!");
            }
            else{
                
                String sql = "INSERT INTO profile"
                     +"(Firstname, Lastname, Gatepass_Type, Platenumber, Vehicle_Type)"
                     +"VALUES (?,?,?,?,?)";
                     
                     pStatement = serverString.prepareStatement(sql);
                     
                     pStatement.setString(1,jTextField_firstName.getText());
                     pStatement.setString(2,jTextField_lastName.getText());
                     pStatement.setString(3, (String) jComboBox_gatepassType.getSelectedItem());
                     pStatement.setString(4, jTextField_platenumber.getText());
                     pStatement.setString(5, jTextField_vehicleType.getText());
                      
                     pStatement.executeUpdate();
                     JOptionPane.showMessageDialog(null, "inserted successfully");

                     }
                
            }
            
                     catch(SQLException | HeadlessException ex){
                     JOptionPane.showMessageDialog(null, ex);
                     }
    }
     private void updateUserDetailsToProfile(){
        try{
                     String sql = "UPDATE profile SET Firstname = ?, Lastname = ?, Gatepass_Type = ?, Platenumber = ?, Vehicle_Type = ? WHERE Barcode ";
                     
//                     serverString = DriverManager.getConnection("jdbc:mysql://localhost/jvpapd?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","1234");
                     pStatement = serverString.prepareStatement(sql);
                     
                     pStatement.setString(1,jTextField_firstName.getText());
                     pStatement.setString(2,jTextField_lastName.getText());
                     pStatement.setString(3, (String) jComboBox_gatepassType.getSelectedItem());
                     pStatement.setString(4, jTextField_platenumber.getText());
                     pStatement.setString(5, jTextField_vehicleType.getText());
                      
                     pStatement.executeUpdate();
                     JOptionPane.showMessageDialog(null, "inserted successfully");

                     }
                     catch(SQLException | HeadlessException ex){
                     JOptionPane.showMessageDialog(null, ex);
                     }
    }
     private void deleteUserDetailsFromProfile(){
        
         try{
            String sql = "DELETE FROM profile WHERE Barcode =?";
            
            pStatement = serverString.prepareStatement(sql);
            pStatement.setString(1,jTextField_barcode.getText());
            pStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "delete successfully");

            }
            catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex);
            }
     }
    public void showTableData(){
                    try{
//                    serverString = DriverManager.getConnection("jdbc:mysql://localhost/jvpapd?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","1234");
                    String sql = "SELECT * FROM profile";
                    pStatement = serverString.prepareStatement(sql);
                    rSet=pStatement.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rSet));
                    }
                    catch(Exception ex){
                    JOptionPane.showMessageDialog(null, ex);

                    }

                    }
    public void transferTableDataToTextField(){
        try{
            
            int row = jTable1.getSelectedRow();
            String tblclick = (jTable1.getModel().getValueAt(row, 0).toString());
            String sql = "select * from profile where Barcode ="+tblclick+"";
            pStatement = serverString.prepareStatement(sql);
            rSet=pStatement.executeQuery();
            if(rSet.next())
            {
                String Barcode = String.valueOf(rSet.getInt("Barcode"));
                jTextField_barcode.setText(Barcode);
                String Firstname = String.valueOf(rSet.getString("Firstname"));
                jTextField_firstName.setText(Firstname);
                String Lastname = String.valueOf(rSet.getString("Lastname"));
                jTextField_lastName.setText(Lastname);
                String Gatepass_Type = String.valueOf(rSet.getString("Gatepass_Type"));
                jComboBox_gatepassType.setSelectedItem(Gatepass_Type);
                String Platenumber = String.valueOf(rSet.getString("Platenumber"));
                jTextField_platenumber.setText(Platenumber);
                String Vehicle_Type = String.valueOf(rSet.getString("Vehicle_Type"));
                jTextField_vehicleType.setText(Vehicle_Type);
                
                
                
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_submit;
    private javax.swing.JComboBox<String> jComboBox_gatepassType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_barcode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Table;
    private javax.swing.JRadioButton jRadioButton_add;
    private javax.swing.JRadioButton jRadioButton_delete;
    private javax.swing.JRadioButton jRadioButton_edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_barcode;
    private javax.swing.JTextField jTextField_firstName;
    private javax.swing.JTextField jTextField_lastName;
    private javax.swing.JTextField jTextField_platenumber;
    private javax.swing.JTextField jTextField_vehicleType;
    // End of variables declaration//GEN-END:variables
}
